### ISSUE TITLE
Preparation

### ISSUE THREAD

**Issue by wyabo** [AllForward/RenewNAT#1]
firstly,I run input_dir=path_to_raw_text_datadata_dir=path_to_binarized_outputsrc=source_languagetgt=target_languagepython3 fairseq_cli/preprocess.py --source-lang ${src} --target-lang ${tgt} --trainpref ${input_dir}/train \ --validpref ${input_dir}/valid --testpref ${input_dir}/test --destdir ${data_dir}/ \--workers 32 --src-dict ${input_dir}/dict.${src}.txt --tgt-dict {input_dir}/dict.${tgt}.txt.
      then,ModuleNotFoundError: No module named 'fairseq'.I checked the source file and found that fairseq exists, and I wonder why I am getting this error.

**Comment by AllForward** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好！您的邮件已查收！

**Comment by AllForward** [comment]
cd RenewNAT
pip install --editable ./

**Comment by AllForward** [comment]
We suggest that this case happens because of the failure of installing fairseq environment. You can follow the next two steps to solve it.
cd RenewNAT
pip install --editable ./

**Comment by wyabo** [comment]
respect！

**Comment by wyabo** [comment]
I ran pip install --editable ./.
     Another error has occurred：preprocess.py: error: unrecognized arguments: --src-dict path_to_raw_text_data/dict.source_language.txt --tgt-dict {input_dir}/dict.target_language.txt


兄弟，这篇文章真牛波儿。我运行了pip install --editable ./后出现了一个警告 
DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found a https://github.com/pypa/pip/issues/12063 我没管它。 然后，继续运行准备阶段的代码，就出现上面的错误了。
